### ISSUE TITLE
curl: (23) Failed writing body

### ISSUE THREAD

**Issue by kingdonb** [teamhephy/workflow-cli#44]
```
Get the deis-cli from new location:
wget https://raw.githubusercontent.com/teamhephy/workflow-cli/master/install-v2.sh && 
chmod +x install-v2.sh && ./install-v2.sh 
```

This is not working for me:

```
$ ./install-v2.sh
Downloading deis-stable-darwin-amd64 From Google Cloud Storage...
Downloading binary from here: https://storage.googleapis.com/hephy-workflow-cli-release/deis-stable-darwin-amd64
curl: (23) Failed writing body (0 != 1380)
```

I used `set -x` and this is the command that fails:

```
curl -fsSL -o deis https://storage.googleapis.com/hephy-workflow-cli-release/deis-stable-darwin-amd64
```

Turns out I have a directory "deis" in my home directory already and that's the problem!

Whoops... carry on then

**Comment by Cryptophobia** [comment]
Sure, @kingdonb if you have an idea how to make the `install-v2.sh` script better we can open a PR. But for now, sounds like everything is working and this would be an improvement of the script.
