### ISSUE TITLE
AccessDenied error when trying to download Windows binaries

### ISSUE THREAD

**Issue by pickettd** [teamhephy/workflow-cli#47]
I tried the links for the 32 bit and 64 bit Windows binaries and got the same 403 error:
https://storage.googleapis.com/workflow-cli-master/deis-latest-windows-amd64.exe
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to workflow-cli-master/deis-latest-windows-amd64.exe.
</Details>
</Error>

**Comment by Cryptophobia** [comment]
Hi @pickettd ,

We have moved all of the former Deis team infrastructure to our own Hephy Google Cloud account. You can find the new cli for Hephy Workflow here:

https://storage.googleapis.com/hephy-workflow-cli-release

To pull the latest builds for the hephy-cli Windows binaries:

Architecture | Link
|---|---|
32-bit | https://storage.googleapis.com/hephy-workflow-cli-release/deis-stable-windows-386.exe
64-bit | https://storage.googleapis.com/hephy-workflow-cli-release/deis-stable-windows-amd64.exe

Thank you for the questions. If there is anything else, let us know. We are also available to help on our slack channel - https://slack.teamhephy.com

**Comment by Cryptophobia** [comment]
Closing this for now, let us know if there is anything else we can help with.
